/* Admin-only Academy console. The server remains the authorization boundary. */
(function(){'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>v?new Date(v).toLocaleDateString('uk-UA'):'—';
window.createAcademyAdmin=function({root,request,onOpenInternal,onClose}){
 let preview=null,busy=false;
 const setStatus=t=>{const el=root.querySelector('#admin-status');if(el)el.textContent=t||'';};
 function shell(){root.innerHTML=`<header class="academy-welcome"><div><span class="academy-eyebrow">TRUEVOICE / INTERNAL</span><h1>Academy Admin</h1><p>Платежі, доступи та внутрішня методологія. Student view залишається основним.</p></div><button class="academy-secondary" id="admin-close">← До кабінету</button></header><div class="academy-admin-grid"><section class="academy-card academy-admin-wide"><div class="academy-card-head"><div><span class="academy-eyebrow">MEMBERS / ORDERS</span><h2>Реєстр доступів</h2></div><button class="academy-secondary" id="admin-refresh">Оновити</button></div><p id="admin-status" role="status"></p><div id="admin-registry" class="academy-admin-list"><p>Завантаження…</p></div></section><section class="academy-card"><span class="academy-eyebrow">WAYFORPAY HISTORY</span><h2>Імпорт історії</h2><form id="history-form" class="academy-admin-form"><label>Від<input id="history-from" type="date" required></label><label>До<input id="history-to" type="date" required></label><button class="academy-secondary">Dry run</button></form><div id="history-preview"></div></section><section class="academy-card"><span class="academy-eyebrow">RECONCILIATION</span><h2>Перевірити оплату</h2><form id="reconcile-form" class="academy-admin-form"><label>orderReference<input id="reconcile-reference" required maxlength="180"></label><button class="academy-secondary">Перевірити</button></form></section><section class="academy-card"><span class="academy-eyebrow">ACCESS</span><h2>Передати доступ</h2><form id="transfer-form" class="academy-admin-form"><label>Order ID<input id="transfer-order" required></label><label>User UUID<input id="transfer-user" required></label><label>Причина<input id="transfer-reason" required minlength="3" maxlength="500"></label><button class="academy-secondary">Transfer</button></form></section><section class="academy-card"><span class="academy-eyebrow">ACCESS</span><h2>Revoke / restore</h2><form id="revoke-form" class="academy-admin-form"><label>Order ID<input id="revoke-order" required></label><label>Дія<select id="revoke-action"><option value="true">Revoke</option><option value="false">Restore</option></select></label><label>Причина<input id="revoke-reason" required minlength="3" maxlength="500"></label><button class="academy-secondary">Застосувати</button></form></section><section class="academy-card"><span class="academy-eyebrow">QA / SYNTHETIC</span><h2>Тестовий реєстр</h2><p>Лише <code>provider=test</code>. Не є доходом і не створює Auth users.</p><div class="academy-button-row"><button class="academy-secondary" id="qa-seed">Seed 7</button><button class="academy-secondary academy-danger" id="qa-cleanup">Cleanup</button></div></section><section class="academy-card"><span class="academy-eyebrow">METHODOLOGY</span><h2>Internal Atlas</h2><p>Службові методологічні поля завантажуються лише після серверної admin-перевірки.</p><button class="academy-primary" id="admin-internal">Відкрити Internal →</button></section></div>`;
 root.querySelector('#admin-close').onclick=()=>onClose?.();root.querySelector('#admin-refresh').onclick=refresh;
 root.querySelector('#history-form').onsubmit=historyPreview;root.querySelector('#reconcile-form').onsubmit=reconcile;root.querySelector('#transfer-form').onsubmit=transfer;root.querySelector('#revoke-form').onsubmit=setRevoked;
 root.querySelector('#qa-seed').onclick=()=>act('qa-seed',{},'QA сценарії створено.',refresh);root.querySelector('#qa-cleanup').onclick=()=>{if(confirm('Видалити всі synthetic provider=test записи?'))act('qa-cleanup',{},'QA записи очищено.',refresh);};root.querySelector('#admin-internal').onclick=()=>onOpenInternal?.();
 }
 function renderRegistry(data){const rows=Array.isArray(data?.orders)?data.orders:[];root.querySelector('#admin-registry').innerHTML=rows.length?rows.map(o=>`<article class="academy-admin-row"><div><strong>${esc(o.productTitle||o.productHint||o.productId||'Unmapped')}</strong><small>${esc(o.reference)} · ${esc(o.buyerEmail)}</small></div><div class="academy-badges"><span class="academy-badge ${o.test?'test':''}">${o.test?'TEST':esc(o.status)}</span>${o.validUntil?`<span class="academy-badge">до ${esc(fmt(o.validUntil))}</span>`:o.resourceKey?'<span class="academy-badge lifetime">lifetime</span>':''}${o.revokedAt?'<span class="academy-badge danger">revoked</span>':''}</div></article>`).join(''):'<p>Платіжних записів поки немає.</p>';}
 async function refresh(){if(busy)return;busy=true;setStatus('Оновлюю реєстр…');try{renderRegistry(await request('registry'));setStatus('Реєстр синхронізовано.');}catch(e){setStatus(e.message);}finally{busy=false;}}
 async function act(action,body,ok,after){if(busy)return;busy=true;setStatus('Виконую…');try{const r=await request(action,body);setStatus(ok);await after?.(r);return r;}catch(e){setStatus(e.message);throw e;}finally{busy=false;}}
 async function historyPreview(e){e.preventDefault();const a=root.querySelector('#history-from').value,b=root.querySelector('#history-to').value;if(!a||!b)return;const dateBegin=Math.floor(new Date(a+'T00:00:00Z').getTime()/1000),dateEnd=Math.floor(new Date(b+'T23:59:59Z').getTime()/1000);try{preview=await act('history-preview',{dateBegin,dateEnd},'Dry run готовий.');const el=root.querySelector('#history-preview'),items=preview.items||[];el.innerHTML=`<div class="academy-preview"><strong>${items.length} транзакцій</strong><small>digest ${esc(preview.digest.slice(0,12))}…</small>${items.slice(0,12).map(x=>`<span>${esc(x.reference||'без reference')} · ${esc(x.classification)}</span>`).join('')}<button class="academy-primary" id="history-commit">Confirm import</button></div>`;el.querySelector('#history-commit').onclick=()=>historyCommit();}catch{}}
 async function historyCommit(){if(!preview)return;if(!confirm('Імпортувати саме цей перевірений WayForPay dry run?'))return;try{await act('history-commit',{dateBegin:preview.dateBegin,dateEnd:preview.dateEnd,digest:preview.digest},'Імпорт завершено.',refresh);preview=null;root.querySelector('#history-preview').replaceChildren();}catch{}}
 async function reconcile(e){e.preventDefault();try{await act('reconcile-reference',{reference:root.querySelector('#reconcile-reference').value.trim()},'Статус перевірено.',refresh);}catch{}}
 async function transfer(e){e.preventDefault();try{await act('transfer-entitlement',{orderId:root.querySelector('#transfer-order').value.trim(),resourceKey:'atlas',targetUserId:root.querySelector('#transfer-user').value.trim(),reason:root.querySelector('#transfer-reason').value.trim()},'Доступ передано.',refresh);}catch{}}
 async function setRevoked(e){e.preventDefault();try{await act('set-revoked',{orderId:root.querySelector('#revoke-order').value.trim(),resourceKey:'atlas',revoked:root.querySelector('#revoke-action').value==='true',reason:root.querySelector('#revoke-reason').value.trim()},'Доступ оновлено.',refresh);}catch{}}
 shell();return{async open(){root.hidden=false;await refresh();},close(){root.hidden=true;},refresh};
};})();
