/* Protected Academy entrypoint. Only the authorized course response boots the original atlas. */
(async function(){'use strict';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let csrf='',account=null,health=null,codeSent=false,captcha='',locked=false,resumeTimer=null,lastResume='',checking=false;
const messages={setup_required:'Підключення кабінету ще налаштовується.',email_setup_required:'Вхід поштовим кодом ще не відкрито: налаштовуємо доставку листів.',email_unavailable:'Поштовий сервіс тимчасово недоступний.',login_required:'Сеанс завершився. Увійди знову.',purchase_required:'Для цієї пошти немає чинного доступу. Напиши в підтримку — перевіримо покупку.',invalid_code:'Код неправильний або вже не діє.',rate_limited:'Забагато спроб. Зачекай і повтори пізніше.'};
const view=mode=>document.documentElement.dataset.memberState=mode;
async function api(action,body){const r=await fetch('/api/academy?action='+encodeURIComponent(action),{method:body===undefined?'GET':'POST',credentials:'same-origin',cache:'no-store',headers:body===undefined?{}:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(20000)});const d=await r.json();if(d.csrf)csrf=d.csrf;if(!r.ok){const e=new Error(messages[d.error]||'Не вдалося виконати запит. Спробуй ще раз.');e.status=r.status;e.data=d;if(account&&[401,403].includes(r.status)&&!['admin-content','logout'].includes(action))lock(e.message);throw e;}return d;}
window.academyApi=api;
function load(src){return new Promise((ok,bad)=>{const s=document.createElement('script');s.src=src+'?v=4-core';s.onload=ok;s.onerror=()=>bad(Error('Не завантажився модуль. Перезавантаж сторінку.'));document.body.append(s);});}
async function pause(){window.pauseAtlasClocks?.();window.breathPacer?.stop();window.focusMode?.close();window.audioEngine?.stopAmbientDrone();window.ambientFX?.stop();const rec=window.voiceRecorder;rec?.cancelPending();if(rec?.isRecording)try{await rec.stopRecording(rec.lessonKey);}catch{}rec?.releaseTracks();rec?.stopVisualizer();}
function lock(message){locked=true;window.academySync?.stop();pause();clearTimeout(resumeTimer);view('gate');$('#login-panel').hidden=false;$('#account-panel').hidden=true;$('#member-nav').hidden=true;$('#login-message').textContent=message;$('#pane')?.replaceChildren();$('#account-panel').replaceChildren();window.LESSONS_DATA=[];window.WEEKS_DATA=[];account=null;}
function dashboard(){const st=window.atlasStorage,s=st.state,ls=window.LESSONS_DATA,l=ls[s.idx]||ls[0],done=st.getTotalCompletedCount(ls),saved=ls.filter(l=>st.isBookmarked(l)||st.getLessonNotes(l));
$('#account-panel').innerHTML=`<header class="academy-welcome"><div><span class="academy-eyebrow">ТВІЙ ОСОБИСТИЙ ПРОСТІР</span><h1>${account.user.name?'З поверненням, '+esc(account.user.name)+'.':'Твій голос починається з тебе.'}</h1><p>${esc(account.user.email)}</p></div><span class="academy-chip">${account.user.role==='admin'?'АДМІН · СТУДЕНТСЬКИЙ ВИГЛЯД':'СТУДЕНТ TRUEVOICE'}</span></header><div class="academy-grid"><div>
<section class="academy-card academy-continue"><img src="assets/brand/logo.svg" alt=""><span class="academy-eyebrow">ПРОДОВЖИТИ ШЛЯХ / 28D ATLAS</span><h2>${esc(l.title)}</h2><p>Тиждень ${l.w} · Урок ${l.n}</p><button class="academy-primary" data-open-lesson="${s.idx}">До практики →</button><div class="academy-stats"><div><strong>${done}/28</strong><span>уроків пройдено</span></div><div><strong>${Math.round(done/28*100)}%</strong><span>твій прогрес</span></div><div><strong>${s.bookmarks.length}</strong><span>закладок</span></div></div></section>
<section class="academy-card" style="margin-top:20px"><span class="academy-eyebrow">КАРТА НАВЧАННЯ</span><h2>28 кроків до себе</h2><div class="academy-progress">${ls.map((l,i)=>`<button class="${st.isLessonDone(l)?'done ':''}${i===s.idx?'current':''}" data-open-lesson="${i}" title="${esc(l.title)}" aria-label="Урок ${i+1}: ${esc(l.title)}">${String(i+1).padStart(2,'0')}</button>`).join('')}</div></section>
<section class="academy-card" style="margin-top:20px"><span class="academy-eyebrow">ЗБЕРЕЖЕНЕ</span><h2>Нотатки та закладки</h2>${saved.length?saved.map(l=>`<button class="academy-note-link" data-open-lesson="${ls.indexOf(l)}">${st.isBookmarked(l)?'★ ':''}${esc(l.title)}<span>${esc(st.getLessonNotes(l)||'Урок у твоїх закладках')}</span></button>`).join(''):'<p>Тут з’являться твої відкриття й уроки, до яких захочеться повернутися.</p>'}</section></div><aside>
<section class="academy-card"><span class="academy-eyebrow">МОЇ ПРОДУКТИ</span><h2>Твоя TrueVoice Academy</h2>${account.purchases.length?account.purchases.map(p=>`<div class="academy-product"><strong>${esc(p.title)}</strong><small>${p.active?'ДОСТУП АКТИВНИЙ':'ДОСТУП НЕАКТИВНИЙ'}${p.expiresAt?' · до '+esc(new Date(p.expiresAt).toLocaleDateString('uk-UA')):''}</small></div>`).join(''):'<p>Доступ адміністратора. Покупок у цьому акаунті немає.</p>'}</section>
<section class="academy-card" style="margin-top:20px"><span class="academy-eyebrow">ПРОФІЛЬ</span><h2>Як до тебе звертатися?</h2><form class="academy-profile" id="profile-form"><label for="profile-name">Ім’я</label><input id="profile-name" maxlength="80" autocomplete="given-name" value="${esc(account.user.name)}"><button class="academy-primary">Зберегти ім’я</button><span id="profile-status" role="status"></span></form></section>
<section class="academy-card" style="margin-top:20px"><span class="academy-eyebrow">ПОРУЧ ІЗ ТОБОЮ</span><h2>Є запитання?</h2><p>Щодо доступу, продуктів або навчання — напиши нам.</p><a href="mailto:hello@truevoice.academy" class="academy-primary">Зв’язатися ↗</a></section></aside></div>`;
$('#account-panel').querySelectorAll('[data-open-lesson]').forEach(b=>b.onclick=()=>openAtlas(Number(b.dataset.openLesson)));
$('#profile-form').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;clearTimeout(resumeTimer);try{const r=await api('profile',{name:$('#profile-name').value,lastLesson:st.getLessonKey(ls[s.idx])});account.user.name=r.name;$('#profile-status').textContent='Ім’я збережено.';}catch(err){if($('#profile-status'))$('#profile-status').textContent=err.message;}finally{b.disabled=false;}};
}
function openAtlas(i){if(!account||locked)return;view('atlas');$('#account-panel').hidden=true;window.atlasApp.navigate(i);window.ambientFX.start();}
async function openAccount(){if(!account||locked)return;await pause();if(!account||locked)return;view('dashboard');$('#account-panel').hidden=false;dashboard();window.scrollTo({top:0,behavior:'auto'});}
async function enter(){account=await api('session');const course=await api('content');window.ATLAS_MEMBER=account.user;window.LESSONS_DATA=course.lessons;window.WEEKS_DATA=course.weeks;document.documentElement.dataset.memberRole=account.user.role;
const seed={idx:Math.max(0,course.lessons.findIndex(l=>`${l.w}-${l.n}`===account.user.lastLesson)),done:{},notes:{},bookmarks:[]};for(const r of account.lessons){seed.done[r.lesson_key]={lesson:r.completed,steps:r.steps};seed.notes[r.lesson_key]=r.notes;if(r.bookmarked)seed.bookmarks.push(r.lesson_key);}window.ATLAS_SEED=seed;
await load('js/member-sync.js');window.academySync=window.createAcademySync(account,api);
for(const name of ['audio-engine','ambient-canvas','breath-pacer','diagrams','voice-recorder','focus-mode','storage'])await load('js/modules/'+name+'.js');window.academySync.restore();view('atlas');await load('js/app.js');
await new Promise((resolve,reject)=>{const until=Date.now()+10000;const check=()=>window.atlasApp?resolve():Date.now()>until?reject(Error('Не завантажився атлас.')):setTimeout(check,30);check();});
$('#login-panel').hidden=true;$('#member-nav').hidden=false;$('#sync-panel').hidden=false;$('#m-int').hidden=account.user.role!=='admin';$('#m-stu').hidden=account.user.role!=='admin';
$('#m-int').onclick=async()=>{if(account?.user.role!=='admin')return;try{const data=await api('admin-content');for(const r of data.lessons){const l=window.LESSONS_DATA.find(l=>l.w===r.w&&l.n===r.n);if(l)l.pain=r.pain;}window.atlasStorage.state.mode='internal';window.atlasApp.navigate(window.atlasStorage.state.idx);}catch(e){alert(e.message);}};
$('#open-account').onclick=openAccount;$('#open-atlas').onclick=()=>openAtlas(window.atlasStorage.state.idx);
$('#logout').onclick=async()=>{const b=$('#logout');b.disabled=true;try{const saved=await window.academySync.flush();if(!saved&&!confirm('Є несинхронізована чернетка. Вийти зараз? Вона залишиться тільки в цій вкладці для твого акаунту.'))return;await pause();await api('logout',{});window.academySync.stop();location.replace(location.pathname);}catch(e){alert(e.message);}finally{b.disabled=false;}};
new MutationObserver(()=>{if(!account||locked)return;const key=window.atlasStorage.getLessonKey(window.LESSONS_DATA[window.atlasStorage.state.idx]);if(key===lastResume)return;lastResume=key;clearTimeout(resumeTimer);resumeTimer=setTimeout(()=>{if(account&&!locked)api('resume',{lesson:key}).catch(()=>{});},600);}).observe($('#pane'),{childList:true});
await openAccount();window.academySync.status();window.academyReady=true;if(/^#lesson-/.test(location.hash))openAtlas(window.atlasStorage.state.idx);
}
// Hidden atlas shortcuts must not change the user's lesson from the dashboard.
document.addEventListener('keydown',e=>{if(document.documentElement.dataset.memberState!=='atlas'&&['ArrowLeft','ArrowRight','m','M','f','F','/'].includes(e.key)&&!e.target.matches('input,textarea,select'))e.stopImmediatePropagation();},true);
$('#login-form').onsubmit=async e=>{e.preventDefault();const b=$('#login-submit');b.disabled=true;try{if(!codeSent){await api('request-code',{email:$('#member-email').value,captchaToken:captcha});codeSent=true;$('#code-field').hidden=false;$('#member-code').required=true;$('#member-email').readOnly=true;$('#change-email').hidden=false;b.textContent='Увійти в кабінет →';$('#member-code').focus();$('#login-message').textContent='Введи код із листа.';}else{await api('verify-code',{email:$('#member-email').value,code:$('#member-code').value});location.reload();}}catch(err){$('#login-message').textContent=err.message;if(!codeSent)window.turnstile?.reset();}finally{b.disabled=!codeSent&&!captcha;}};
$('#change-email').onclick=()=>{codeSent=false;$('#code-field').hidden=true;$('#member-code').required=false;$('#member-email').readOnly=false;$('#member-code').value='';$('#change-email').hidden=true;$('#login-submit').textContent='Отримати код →';captcha='';$('#login-submit').disabled=true;window.turnstile?.reset();};
async function checkSession(){if(!account||locked||document.hidden||checking)return;checking=true;try{await api('session');}catch{}finally{checking=false;}}
setInterval(checkSession,60000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)checkSession();});
try{health=await api('health');if(!health.configured){$('#login-message').textContent=messages.setup_required;$('#login-submit').textContent='Вхід ще не налаштований';return;}
try{await enter();return;}catch(e){if(account)lock(e.message);if(![401,403].includes(e.status))throw e;$('#login-message').textContent=e.status===403?e.message:'';}
if(!health.emailEnabled){$('#login-submit').textContent='Вхід незабаром';$('#login-message').textContent=messages.email_setup_required;return;}
const script=document.createElement('script');script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';script.onload=()=>window.turnstile.render('#captcha',{sitekey:health.captchaSiteKey,callback:t=>{captcha=t;$('#login-submit').disabled=false;},'expired-callback':()=>{captcha='';if(!codeSent)$('#login-submit').disabled=true;}});script.onerror=()=>$('#login-message').textContent='Не завантажилася перевірка безпеки. Онови сторінку.';document.head.append(script);$('#login-submit').textContent='Отримати код →';
}catch(e){view('gate');$('#login-panel').hidden=false;$('#login-message').textContent=e.message;$('#login-submit').textContent='Спробуй пізніше';}
})();
