/* TrueVoice Academy entrypoint: account first, protected Atlas lazy-loaded only with active access. */
(async function(){'use strict';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let csrf='',account=null,health=null,codeSent=false,captcha='',resumeTimer=null,lastResume='',checking=false,atlasReady=false,atlasBooting=null,adminController=null,sessionLocked=false;
const loaded=new Set();
const messages={setup_required:'Підключення кабінету ще налаштовується.',email_setup_required:'Вхід поштовим кодом ще не відкрито: налаштовуємо доставку листів.',email_unavailable:'Поштовий сервіс тимчасово недоступний.',login_required:'Сеанс завершився. Увійди знову.',purchase_required:'Atlas зараз недоступний для цього акаунта. Перевір статус продукту або напиши в підтримку.',invalid_code:'Код неправильний або вже не діє.',rate_limited:'Забагато спроб. Зачекай і повтори пізніше.',admin_required:'Потрібен admin-доступ.',provider_unavailable:'WayForPay тимчасово недоступний. Спробуй пізніше.'};
const view=mode=>document.documentElement.dataset.memberState=mode;
function errFor(d){return messages[d?.error]||'Не вдалося виконати запит. Спробуй ще раз.';}
async function api(action,body){const r=await fetch('/api/academy?action='+encodeURIComponent(action),{method:body===undefined?'GET':'POST',credentials:'same-origin',cache:'no-store',headers:body===undefined?{}:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(20000)}),d=await r.json();if(d.csrf)csrf=d.csrf;if(!r.ok){const e=new Error(errFor(d));e.status=r.status;e.data=d;if(r.status===401&&account)lockSession(e.message);throw e;}return d;}
async function paymentApi(action,body){const r=await fetch('/api/payments?action='+encodeURIComponent(action),{method:body===undefined?'GET':'POST',credentials:'same-origin',cache:'no-store',headers:body===undefined?{}:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(30000)}),d=await r.json();if(!r.ok){const e=new Error(errFor(d));e.status=r.status;e.data=d;if(r.status===401)lockSession(e.message);throw e;}return d.result;}
window.academyApi=api;
function load(src){if(loaded.has(src))return Promise.resolve();return new Promise((ok,bad)=>{const s=document.createElement('script');s.src=src+'?v=4.1-academy';s.onload=()=>{loaded.add(src);ok();};s.onerror=()=>bad(Error('Не завантажився модуль. Перезавантаж сторінку.'));document.body.append(s);});}
async function pause(){window.pauseAtlasClocks?.();window.breathPacer?.stop();window.focusMode?.close();window.audioEngine?.stopAmbientDrone();window.ambientFX?.stop();const rec=window.voiceRecorder;rec?.cancelPending();if(rec?.isRecording)try{await rec.stopRecording(rec.lessonKey);}catch{}rec?.releaseTracks();rec?.stopVisualizer();}
function lockSession(message){sessionLocked=true;clearTimeout(resumeTimer);window.academySync?.stop();pause();view('gate');$('#login-panel').hidden=false;$('#account-panel').hidden=true;$('#admin-panel').hidden=true;$('#member-nav').hidden=true;$('#sync-panel').hidden=true;$('#login-message').textContent=message;$('#pane')?.replaceChildren();window.LESSONS_DATA=[];window.WEEKS_DATA=[];account=null;}
const keyFor=i=>`${Math.floor(i/7)+1}-${i%7+1}`,indexFor=key=>{const m=/^([1-4])-([1-7])$/.exec(String(key||''));return m?(Number(m[1])-1)*7+Number(m[2])-1:0;};
function productState(p){if(p.status==='refunded')return['REFUNDED','danger'];if(p.status==='chargeback')return['CHARGEBACK','danger'];if(p.status==='review'||p.status==='pending')return['REVIEW','review'];if(p.active&&p.lifetime)return['LIFETIME','lifetime'];if(p.active)return['АКТИВНИЙ','active'];if(p.status==='approved'&&p.expiresAt)return['ЗАВЕРШЕНО','expired'];return[String(p.status||'НЕАКТИВНИЙ').toUpperCase(),'expired'];}
function productCards(){if(!account.purchases?.length)return account.user.role==='admin'?'<p>Admin-доступ. Комерційних покупок у цьому акаунті немає.</p>':'<p>Покупок для цієї пошти поки не знайдено.</p>';return account.purchases.map(p=>{const [label,kind]=productState(p);return`<div class="academy-product"><div><strong>${esc(p.title)}</strong><small>${p.expiresAt?'Доступ до '+esc(new Date(p.expiresAt).toLocaleDateString('uk-UA')):p.lifetime?'Безстроковий доступ':esc(p.status)}</small></div><div class="academy-badges"><span class="academy-badge ${kind}">${esc(label)}</span>${p.test?'<span class="academy-badge test">TEST</span>':''}</div></div>`;}).join('');}
function dashboard(){const lessons=Array.isArray(account.lessons)?account.lessons:[],done=lessons.filter(x=>x.completed).length,bookmarks=lessons.filter(x=>x.bookmarked).length,last=indexFor(account.user.lastLesson),active=account.access?.atlas===true;
 $('#account-panel').innerHTML=`<header class="academy-welcome"><div><span class="academy-eyebrow">ТВІЙ ОСОБИСТИЙ ПРОСТІР</span><h1>${account.user.name?'З поверненням, '+esc(account.user.name)+'.':'Твій голос починається з тебе.'}</h1><p>${esc(account.user.email)}</p></div><span class="academy-chip">${account.user.role==='admin'?'АДМІН · СТУДЕНТСЬКИЙ ВИГЛЯД':'СТУДЕНТ TRUEVOICE'}</span></header><div class="academy-grid"><div>
 <section class="academy-card academy-continue ${active?'':'academy-locked'}"><img src="assets/brand/logo.svg" alt=""><span class="academy-eyebrow">TRUEVOICE / 28D ATLAS</span><h2>${active?'Продовжити свій шлях':'Atlas зараз закритий'}</h2><p>${active?`Наступна точка · ${esc(account.user.lastLesson)}`:'Кабінет і твоя історія залишаються доступними. Для практик потрібен активний entitlement.'}</p>${active?`<button class="academy-primary" data-open-lesson="${last}">До практики →</button>`:'<div class="academy-button-row"><button class="academy-secondary" id="check-access">Перевірити доступ</button><a class="academy-primary" href="mailto:hello@truevoice.academy">Підтримка ↗</a></div>'}<div class="academy-stats"><div><strong>${done}/28</strong><span>уроків пройдено</span></div><div><strong>${Math.round(done/28*100)}%</strong><span>прогрес</span></div><div><strong>${bookmarks}</strong><span>закладок</span></div></div></section>
 <section class="academy-card" style="margin-top:20px"><span class="academy-eyebrow">КАРТА НАВЧАННЯ</span><h2>28 кроків до себе</h2><div class="academy-progress">${Array.from({length:28},(_,i)=>{const row=lessons.find(x=>x.lesson_key===keyFor(i));return`<button class="${row?.completed?'done ':''}${i===last?'current':''}" ${active?`data-open-lesson="${i}"`:'disabled'} aria-label="Урок ${i+1}${active?'':' — доступ закритий'}">${String(i+1).padStart(2,'0')}</button>`;}).join('')}</div></section>
 <section class="academy-card" style="margin-top:20px"><span class="academy-eyebrow">ЖУРНАЛ</span><h2>Нотатки та закладки</h2><p>${lessons.some(x=>x.notes||x.bookmarked)?`${lessons.filter(x=>x.notes||x.bookmarked).length} збережених точок у твоєму Atlas.`:'Тут з’являтимуться твої нотатки й закладки після практик.'}</p></section></div><aside>
 <section class="academy-card"><span class="academy-eyebrow">МОЇ ПРОДУКТИ</span><h2>TrueVoice Academy</h2>${productCards()}</section>
 <section class="academy-card" style="margin-top:20px"><span class="academy-eyebrow">ПРОФІЛЬ</span><h2>Твій профіль</h2><form class="academy-profile" id="profile-form"><label>Пошта<input value="${esc(account.user.email)}" readonly aria-readonly="true"></label><label for="profile-name">Ім’я<input id="profile-name" maxlength="80" autocomplete="given-name" value="${esc(account.user.name)}"></label><button class="academy-primary">Зберегти ім’я</button><span id="profile-status" role="status"></span></form></section>
 <section class="academy-card" style="margin-top:20px"><span class="academy-eyebrow">ПОРУЧ ІЗ ТОБОЮ</span><h2>Є запитання?</h2><p>Щодо доступу, продуктів або навчання — напиши нам.</p><a href="mailto:hello@truevoice.academy" class="academy-primary">Зв’язатися ↗</a></section></aside></div>`;
 $('#account-panel').querySelectorAll('[data-open-lesson]').forEach(b=>b.onclick=()=>openAtlas(Number(b.dataset.openLesson)));
 $('#check-access')?.addEventListener('click',refreshAccount);
 $('#profile-form').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{const r=await api('profile',{name:$('#profile-name').value,lastLesson:account.user.lastLesson||'1-1'});account.user.name=r.name;$('#profile-status').textContent='Ім’я збережено.';}catch(err){$('#profile-status').textContent=err.message;}finally{b.disabled=false;}};
}
function setNav(){if(!account)return;$('#member-nav').hidden=false;$('#open-admin').hidden=account.user.role!=='admin';$('#open-atlas').disabled=account.access?.atlas!==true;$('#open-atlas').title=account.access?.atlas?'':'Atlas недоступний для цього акаунта';}
async function wipeAtlasAfterAccessLoss(){if(!atlasReady)return;await pause();clearTimeout(resumeTimer);lastResume='';window.academySync?.stop();$('#pane')?.replaceChildren();window.LESSONS_DATA=[];window.WEEKS_DATA=[];window.ATLAS_SEED=null;$('#sync-panel').hidden=true;atlasReady=false;}
async function bootAtlas(){if(atlasReady)return;if(atlasBooting)return atlasBooting;if(account?.access?.atlas!==true)throw Object.assign(Error(messages.purchase_required),{status:403});atlasBooting=(async()=>{const course=await api('content');window.ATLAS_MEMBER=account.user;window.LESSONS_DATA=course.lessons;window.WEEKS_DATA=course.weeks;const seed={idx:Math.max(0,course.lessons.findIndex(l=>`${l.w}-${l.n}`===account.user.lastLesson)),done:{},notes:{},bookmarks:[]};for(const r of account.lessons||[]){seed.done[r.lesson_key]={lesson:r.completed,steps:r.steps};seed.notes[r.lesson_key]=r.notes;if(r.bookmarked)seed.bookmarks.push(r.lesson_key);}window.ATLAS_SEED=seed;await load('js/member-sync.js');window.academySync=window.createAcademySync(account,api);for(const name of ['audio-engine','ambient-canvas','breath-pacer','diagrams','voice-recorder','focus-mode','storage'])await load('js/modules/'+name+'.js');window.academySync.restore();view('atlas');await load('js/app.js');await new Promise((resolve,reject)=>{const until=Date.now()+10000,check=()=>window.atlasApp?resolve():Date.now()>until?reject(Error('Не завантажився атлас.')):setTimeout(check,30);check();});$('#sync-panel').hidden=false;$('#m-int')?.setAttribute('hidden','');$('#m-stu')?.setAttribute('hidden','');new MutationObserver(()=>{if(!account||!atlasReady||document.documentElement.dataset.memberState!=='atlas')return;const key=window.atlasStorage.getLessonKey(window.LESSONS_DATA[window.atlasStorage.state.idx]);if(key===lastResume)return;lastResume=key;account.user.lastLesson=key;clearTimeout(resumeTimer);resumeTimer=setTimeout(()=>api('resume',{lesson:key}).catch(()=>{}),600);}).observe($('#pane'),{childList:true});atlasReady=true;window.academySync.status();})().finally(()=>atlasBooting=null);return atlasBooting;}
async function openAtlas(i=indexFor(account?.user?.lastLesson)){if(!account||sessionLocked||account.access?.atlas!==true){await openAccount();return;}try{await bootAtlas();window.atlasStorage.state.mode='student';$('#account-panel').hidden=true;$('#admin-panel').hidden=true;view('atlas');window.atlasApp.navigate(Number.isInteger(i)?i:window.atlasStorage.state.idx);window.ambientFX.start();}catch(e){await openAccount();$('#account-panel').insertAdjacentHTML('afterbegin',`<p class="academy-alert">${esc(e.message)}</p>`);}}
async function openInternal(){if(account?.user?.role!=='admin')return;await bootAtlas();const data=await api('admin-content');for(const r of data.lessons){const l=window.LESSONS_DATA.find(l=>l.w===r.w&&l.n===r.n);if(l)l.pain=r.pain;}window.atlasStorage.state.mode='internal';$('#account-panel').hidden=true;$('#admin-panel').hidden=true;view('atlas');window.atlasApp.navigate(window.atlasStorage.state.idx);}
async function openAccount(){if(!account||sessionLocked)return;if(atlasReady)await pause();adminController?.close();view('dashboard');$('#admin-panel').hidden=true;$('#account-panel').hidden=false;dashboard();setNav();window.scrollTo({top:0,behavior:'auto'});}
async function openAdmin(){if(account?.user?.role!=='admin')return;if(atlasReady)await pause();view('dashboard');$('#account-panel').hidden=true;$('#admin-panel').hidden=false;if(!adminController){await load('js/academy-admin.js');adminController=window.createAcademyAdmin({root:$('#admin-panel'),request:paymentApi,onOpenInternal:openInternal,onClose:openAccount});}await adminController.open();window.scrollTo({top:0,behavior:'auto'});}
async function applyFreshAccount(fresh){const lost=account?.access?.atlas===true&&fresh.access?.atlas!==true;account=fresh;document.documentElement.dataset.memberRole=account.user.role;if(lost)await wipeAtlasAfterAccessLoss();await openAccount();}
async function refreshAccount(){try{await applyFreshAccount(await api('session'));}catch(e){if(e.status!==401)$('#account-panel')?.insertAdjacentHTML('afterbegin',`<p class="academy-alert">${esc(e.message)}</p>`);}}
window.refreshAcademyAccount=refreshAccount;
async function enter(){account=await api('session');sessionLocked=false;document.documentElement.dataset.memberRole=account.user.role;$('#login-panel').hidden=true;setNav();$('#open-account').onclick=openAccount;$('#open-atlas').onclick=()=>openAtlas();$('#open-admin').onclick=openAdmin;$('#logout').onclick=logout;await openAccount();window.academyReady=true;if(/^#lesson-/.test(location.hash)&&account.access?.atlas)await openAtlas(indexFor(account.user.lastLesson));}
async function logout(){const b=$('#logout');b.disabled=true;try{if(window.academySync){const saved=await window.academySync.flush();if(!saved&&!confirm('Є несинхронізована чернетка. Вийти зараз?'))return;}await pause();await api('logout',{});window.academySync?.stop();location.replace(location.pathname);}catch(e){alert(e.message);}finally{b.disabled=false;}}
document.addEventListener('keydown',e=>{if(document.documentElement.dataset.memberState!=='atlas'&&['ArrowLeft','ArrowRight','m','M','f','F','/'].includes(e.key)&&!e.target.matches('input,textarea,select'))e.stopImmediatePropagation();},true);
$('#login-form').onsubmit=async e=>{e.preventDefault();const b=$('#login-submit');b.disabled=true;try{if(!codeSent){await api('request-code',{email:$('#member-email').value,captchaToken:captcha});codeSent=true;$('#code-field').hidden=false;$('#member-code').required=true;$('#member-email').readOnly=true;$('#change-email').hidden=false;b.textContent='Увійти в кабінет →';$('#member-code').focus();$('#login-message').textContent='Введи код із листа.';}else{await api('verify-code',{email:$('#member-email').value,code:$('#member-code').value});location.reload();}}catch(err){$('#login-message').textContent=err.message;if(!codeSent)window.turnstile?.reset();}finally{b.disabled=!codeSent&&!captcha;}};
$('#change-email').onclick=()=>{codeSent=false;$('#code-field').hidden=true;$('#member-code').required=false;$('#member-email').readOnly=false;$('#member-code').value='';$('#change-email').hidden=true;$('#login-submit').textContent='Отримати код →';captcha='';$('#login-submit').disabled=true;window.turnstile?.reset();};
async function checkSession(){if(!account||sessionLocked||document.hidden||checking)return;checking=true;try{const fresh=await api('session');const changed=fresh.access?.atlas!==account.access?.atlas||fresh.user.role!==account.user.role;if(changed)await applyFreshAccount(fresh);else account=fresh;}catch{}finally{checking=false;}}
setInterval(checkSession,60000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)checkSession();});
try{health=await api('health');if(!health.configured){$('#login-message').textContent=messages.setup_required;$('#login-submit').textContent='Вхід ще не налаштований';return;}try{await enter();return;}catch(e){if(e.status!==401)throw e;}
 if(!health.emailEnabled){$('#login-submit').textContent='Вхід незабаром';$('#login-message').textContent=messages.email_setup_required;return;}const script=document.createElement('script');script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';script.onload=()=>window.turnstile.render('#captcha',{sitekey:health.captchaSiteKey,callback:t=>{captcha=t;$('#login-submit').disabled=false;},'expired-callback':()=>{captcha='';if(!codeSent)$('#login-submit').disabled=true;}});script.onerror=()=>$('#login-message').textContent='Не завантажилася перевірка безпеки. Онови сторінку.';document.head.append(script);$('#login-submit').textContent='Отримати код →';
}catch(e){view('gate');$('#login-panel').hidden=false;$('#login-message').textContent=e.message;$('#login-submit').textContent='Спробуй пізніше';}
})();
