const {test}=require('node:test'),assert=require('node:assert/strict');
const {createPayments}=require('../server/payments.cjs'),wfp=require('../server/wayforpay.cjs');
const {createHandler}=require('../server/payments-api.cjs');
const {fixture,seed,scalar,A,C}=require('./db-fixture.cjs');

function memoryClient(){const orders=new Map(),events=new Set(),audits=[];return{orders,audits,rpc:async(name,a)=>{
 if(name==='tv_payment_order'){const o=orders.get(a.p_reference);return o?{data:o,error:null}:{data:null,error:{code:'22023'}};}
 if(name==='tv_register_order'){const existing=orders.get(a.p_reference);if(existing)return{data:{orderId:existing.orderId,status:existing.status},error:null};const o={orderId:'wayforpay:'+a.p_reference,reference:a.p_reference,productId:a.p_product_id,amountMinor:a.p_amount_minor,currency:a.p_currency,status:'pending',purchasedAt:a.p_purchased_at};orders.set(a.p_reference,o);return{data:{orderId:o.orderId,status:'pending'},error:null};}
 if(name==='tv_apply_payment_status'){const key=a.p_event_key;if(events.has(key)){const o=orders.get(a.p_reference);return{data:{orderId:o.orderId,status:o.status,duplicate:true},error:null};}events.add(key);const o=orders.get(a.p_reference);o.status=(['refunded','chargeback'].includes(o.status)&&a.p_status==='approved')?o.status:a.p_status;return{data:{orderId:o.orderId,status:o.status,duplicate:false},error:null};}
 if(name==='tv_admin_audit'){audits.push(a);return{data:{id:audits.length},error:null};}
 if(name==='tv_admin_registry')return{data:{orders:[...orders.values()]},error:null};
 if(name==='tv_admin_transfer_entitlement'||name==='tv_admin_set_revoked'||name==='tv_mark_reconciled')return{data:{ok:true},error:null};
 return{data:null,error:{code:'unknown'}};
}};}
function provider(history){return{...wfp,fetchTransactionList:async()=>({transactionList:history}),fetchCheckStatus:async(_cfg,ref)=>({merchantAccount:'m',orderReference:ref,amount:ref.includes('base')?'15.00':'19.00',currency:'USD',authCode:'A',cardPan:'44****1111',transactionStatus:'Approved',reasonCode:1100,processingDate:1700000100,merchantSignature:'ok'}),verifyStatusResponse:()=>true};}
const baseTx={orderReference:'tv-base-1700000000-a1',amount:'15.00',currency:'USD',email:'buyer@example.test',createdDate:1700000000,transactionStatus:'Approved'};
const unknownTx={orderReference:'legacy-unknown',amount:'19.00',currency:'USD',email:'legacy@example.test',createdDate:1700000000,transactionStatus:'Approved',productName:'Old offer'};

test('history window is capped at 31 days',async()=>{const p=createPayments({client:memoryClient(),provider:provider([]),providerConfig:{merchantAccount:'m',secret:'s',legacyRules:[]}});await assert.rejects(p.buildHistoryPreview({dateBegin:0,dateEnd:31*86400+1}),e=>e.code==='invalid_history_window'&&e.status===400);});
test('history preview maps Mini expiry from provider purchase time and unknown product to review',async()=>{const p=createPayments({client:memoryClient(),provider:provider([baseTx,unknownTx]),providerConfig:{merchantAccount:'m',secret:'s',legacyRules:[]}}),v=await p.buildHistoryPreview({dateBegin:1699990000,dateEnd:1700010000});const mini=v.items.find(x=>x.reference===baseTx.orderReference),unknown=v.items.find(x=>x.reference===unknownTx.orderReference);assert.equal(mini.productId,'mini-base');assert.equal(mini.expiresAt,new Date(new Date(mini.purchasedAt).getTime()+210*86400000).toISOString());assert.equal(unknown.productId,null);assert.equal(unknown.classification,'review');assert.match(v.digest,/^[a-f0-9]{64}$/);});
test('history digest mismatch blocks all writes',async()=>{const c=memoryClient(),p=createPayments({client:c,provider:provider([baseTx]),providerConfig:{merchantAccount:'m',secret:'s',legacyRules:[]}});await assert.rejects(p.historyCommit({actorId:C,dateBegin:1699990000,dateEnd:1700010000,digest:'0'.repeat(64)}),e=>e.code==='history_changed'&&e.status===409);assert.equal(c.orders.size,0);});
test('same history commit twice is idempotent and unknown product persists review',async()=>{const c=memoryClient(),p=createPayments({client:c,provider:provider([baseTx,unknownTx]),providerConfig:{merchantAccount:'m',secret:'s',legacyRules:[]}}),preview=await p.buildHistoryPreview({dateBegin:1699990000,dateEnd:1700010000});const a=await p.historyCommit({actorId:C,dateBegin:1699990000,dateEnd:1700010000,digest:preview.digest}),b=await p.historyCommit({actorId:C,dateBegin:1699990000,dateEnd:1700010000,digest:preview.digest});assert.equal(c.orders.size,2);assert.equal(c.orders.get('legacy-unknown').productId,null);assert.equal(c.orders.get('legacy-unknown').status,'review');assert.equal(a.digest,b.digest);assert.equal(c.audits.length,2);});

test('admin SQL transfer/revoke is actor-checked and keeps financial buyer email unchanged',async()=>{const db=await fixture();try{await seed(db);await db.exec(`insert into tv_core.member_roles(user_id,role) values('${C}','admin')`);await assert.rejects(db.query('select public.tv_admin_registry($1)',[A]),/admin required/);const before=(await scalar(db,"select buyer_email from tv_core.orders where id='o-a'")).buyer_email;await db.query('select public.tv_admin_transfer_entitlement($1,$2,$3,$4,$5)',[C,'o-a','atlas',C,'support verified ownership']);assert.equal((await scalar(db,"select user_id from tv_core.entitlements where order_id='o-a'")).user_id,C);assert.equal((await scalar(db,"select buyer_email from tv_core.orders where id='o-a'")).buyer_email,before);await db.query('select public.tv_admin_set_revoked($1,$2,$3,$4,$5)',[C,'o-a','atlas',true,'manual support revoke']);assert.ok((await scalar(db,"select revoked_at from tv_core.entitlements where order_id='o-a'")).revoked_at);await db.query('select public.tv_admin_set_revoked($1,$2,$3,$4,$5)',[C,'o-a','atlas',false,'manual support restore']);assert.equal((await scalar(db,"select revoked_at from tv_core.entitlements where order_id='o-a'")).revoked_at,null);await db.exec("update tv_core.orders set status='refunded' where id='o-a'");await assert.rejects(db.query('select public.tv_admin_set_revoked($1,$2,$3,$4,$5)',[C,'o-a','atlas',false,'try restore terminal']),/terminal order cannot restore/);assert.equal((await scalar(db,"select has_function_privilege('authenticated','public.tv_admin_registry(uuid)','execute') allowed")).allowed,false);}finally{await db.close();}});

function res(){return{statusCode:0,headers:{},setHeader(k,v){this.headers[k.toLowerCase()]=v;},status(n){this.statusCode=n;return this;},json(b){this.body=b;return this;}};}
test('student cannot enter payment registry',async()=>{const e=Object.assign(new Error('admin_required'),{status:403,code:'admin_required'}),r=res(),handler=createHandler({payments:{},adminAuthorizer:async()=>{throw e;},config:{academyConfig:{url:'x',key:'x',origins:['https://atlas.example'],local:false}}});await handler({url:'/api/payments?action=registry',method:'GET',headers:{}},r);assert.equal(r.statusCode,403);assert.equal(r.body.error,'admin_required');});
