// Synthetic auth/payment harness, localhost only. Never imported by production or copied to dist.
const http=require('node:http'),fs=require('node:fs/promises'),path=require('node:path');
const {createHandler}=require('../server/academy.cjs');
const {fixture,seed,claims,A,B,C,SA,SB,SC}=require('./db-fixture.cjs');
const D='10000000-0000-4000-8000-000000000004',E='10000000-0000-4000-8000-000000000005',SD='20000000-0000-4000-8000-000000000004',SE='20000000-0000-4000-8000-000000000005';
async function start(){const db=await fixture();await seed(db);await db.exec(`insert into auth.users(id,email,email_confirmed_at) values('${D}','d@example.test',now()),('${E}','e@example.test',now());insert into auth.sessions(id,user_id) values('${SD}','${D}'),('${SE}','${E}');insert into tv_core.member_roles(user_id,role) values('${C}','admin');insert into tv_core.orders(id,provider,reference,buyer_email,product_id,amount_minor,currency,status,verified_at,purchased_at,status_observed_at) values('o-e','test','expired-e','e@example.test','mini-base',1500,'USD','approved',now(),now()-interval '211 days',now());insert into tv_core.entitlements(order_id,resource_key,user_id,valid_from,valid_until) values('o-e','atlas','${E}',now()-interval '211 days',now()-interval '1 day');`);
 let queue=Promise.resolve();const serial=fn=>{const p=queue.then(fn);queue=p.catch(()=>{});return p;};const config={url:'https://test.supabase.co',key:'test-public',origins:['http://127.0.0.1:8081'],emailEnabled:false,local:true},ids={A:[A,SA],B:[B,SB],C:[C,SC],D:[D,SD],E:[E,SE]};
 const handler=createHandler({config,clientFactory:(req,res)=>{const key=(req.headers.cookie||'').match(/(?:^|;\s*)fixture=([ABCDE])(?:;|$)/)?.[1],id=ids[key];return{auth:{getUser:async()=>id?{data:{user:{id:id[0],email:key.toLowerCase()+'@example.test',email_confirmed_at:new Date().toISOString()}}}:{data:{user:null},error:{status:401}},signOut:async()=>{res.setHeader('Set-Cookie','fixture=; Path=/; Max-Age=0');return{error:null};}},rpc:async(name,args)=>serial(async()=>{if(!id)return{data:null,error:{code:'42501'}};try{await claims(db,...id);let sql,params=[];if(name==='tv_account')sql='select public.tv_account() v';else if(name==='tv_authorize')sql='select public.tv_authorize() v';else if(name==='tv_set_resume'){sql='select public.tv_set_resume($1) v';params=[args.p_lesson];}else if(name==='tv_save_lesson'){sql='select public.tv_save_lesson($1,$2,$3) v';params=[args.p_lesson,args.p_version,args.p_data];}else if(name==='tv_save_profile'){sql='select public.tv_save_profile($1,$2) v';params=[args.p_name,args.p_last_lesson];}else throw Error('unknown RPC');return{data:(await db.query(sql,params)).rows[0].v,error:null};}catch(e){return{data:null,error:{code:e.code||'500'}};}finally{await db.exec('reset role');}})};}});
 async function localPayments(req,res,url){const key=(req.headers.cookie||'').match(/(?:^|;\s*)fixture=([ABCDE])(?:;|$)/)?.[1];if(key!=='C')return res.status(403).json({error:'admin_required'});const action=url.searchParams.get('action');if(action==='registry'){const rows=await serial(async()=>{await db.exec('reset role');return(await db.query(`select o.id,o.provider,o.reference,o.buyer_email,o.product_id,p.title,o.status,o.purchased_at,e.resource_key,e.valid_until,e.revoked_at from tv_core.orders o left join tv_core.products p on p.id=o.product_id left join tv_core.entitlements e on e.order_id=o.id order by o.purchased_at desc`)).rows;});return res.status(200).json({ok:true,result:{orders:rows.map(x=>({orderId:x.id,provider:x.provider,reference:x.reference,buyerEmail:x.buyer_email,productId:x.product_id,productTitle:x.title,status:x.status,purchasedAt:x.purchased_at,resourceKey:x.resource_key,validUntil:x.valid_until,revokedAt:x.revoked_at,test:x.provider==='test'}))}});}
  let raw='';for await(const chunk of req)raw+=chunk;let body={};try{body=raw?JSON.parse(raw):{};}catch{}if(action==='history-preview')return res.status(200).json({ok:true,result:{dateBegin:body.dateBegin,dateEnd:body.dateEnd,digest:'a'.repeat(64),items:[]}});if(action==='history-commit')return res.status(200).json({ok:true,result:{digest:body.digest,results:[]}});if(action==='reconcile-reference')return res.status(200).json({ok:true,result:{reference:body.reference,status:'approved'}});if(action==='qa-seed')return res.status(200).json({ok:true,result:{count:7}});if(action==='qa-cleanup')return res.status(200).json({ok:true,result:{orders:7}});if(action==='transfer-entitlement'||action==='set-revoked')return res.status(200).json({ok:true,result:{ok:true}});return res.status(404).json({error:'not_found'});}
 const root=path.resolve('dist'),server=http.createServer(async(req,res)=>{res.status=n=>{res.statusCode=n;return res;};res.json=d=>{res.setHeader('Content-Type','application/json');res.end(JSON.stringify(d));};const url=new URL(req.url,'http://127.0.0.1:8081');if(url.pathname==='/api/academy')return handler(req,res);if(url.pathname==='/api/payments')return localPayments(req,res,url);try{const file=path.resolve(root,'.'+decodeURIComponent(url.pathname==='/'?'/index.html':url.pathname));if(!file.startsWith(root+path.sep))throw Error('denied');const data=await fs.readFile(file),type={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.webp':'image/webp','.json':'application/json'}[path.extname(file)]||'application/octet-stream';res.setHeader('Content-Type',type);res.setHeader('Cache-Control','no-store');res.end(data);}catch{res.statusCode=404;res.end('Not found');}});await new Promise(ok=>server.listen(8081,'127.0.0.1',ok));return{server,db,serial,ids:{A,B,C,D,E},close:async()=>{await new Promise(ok=>server.close(ok));await db.close();}};}
module.exports={start,D,E,SD,SE};
