const {test}=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {createPayments}=require('../server/payments.cjs');
const wfp=require('../server/wayforpay.cjs');
const cfg={merchantAccount:'m',secret:'s',legacyRules:[]};
const signed=(over={})=>{const p={merchantAccount:'m',orderReference:'tv-base-1700000000-a1',amount:'15.00',currency:'USD',authCode:'A1',cardPan:'44****1111',transactionStatus:'Approved',reasonCode:1100,processingDate:1700000060,...over};p.merchantSignature=crypto.createHmac('md5','s').update(['merchantAccount','orderReference','amount','currency','authCode','cardPan','transactionStatus','reasonCode'].map(k=>p[k]).join(';')).digest('hex');return p;};
function fakeClient(expected={amountMinor:1500,currency:'USD'}){const calls=[];return{calls,rpc:async(name,args)=>{calls.push([name,args]);if(name==='tv_register_order')return{data:{orderId:'o1',status:'pending'},error:null};if(name==='tv_payment_order')return{data:{orderId:'o1',reference:args.p_reference,productId:'mini-base',amountMinor:expected.amountMinor,currency:expected.currency,status:'pending',purchasedAt:'2023-11-14T22:13:20.000Z'},error:null};if(name==='tv_apply_payment_status')return{data:{orderId:'o1',status:args.p_status,duplicate:false},error:null};return{data:null,error:{code:'unknown'}};}};}
const fetchFor=payload=>async()=>({ok:true,json:async()=>payload});

test('trusted order registration persists normalized checkout identity',async()=>{const client=fakeClient(),payments=createPayments({client,provider:wfp,providerConfig:cfg,fetchImpl:fetchFor(signed())});await payments.registerTrustedOrder({reference:'tv-base-1700000000-a1',email:' Buyer@Example.Test ',productId:'mini-base',amountMinor:1500,currency:'usd',purchasedAt:1700000000});const [name,args]=client.calls[0];assert.equal(name,'tv_register_order');assert.equal(args.p_buyer_email,'buyer@example.test');assert.equal(args.p_amount_minor,1500);assert.equal(args.p_currency,'USD');assert.equal(args.p_product_id,'mini-base');assert.match(args.p_payload_hash,/^[a-f0-9]{64}$/);});
test('verified CHECK_STATUS approval uses registered amount and currency',async()=>{const client=fakeClient(),payments=createPayments({client,provider:wfp,providerConfig:cfg,fetchImpl:fetchFor(signed())});const r=await payments.verifyAndApplyReference('tv-base-1700000000-a1');const apply=client.calls.find(x=>x[0]==='tv_apply_payment_status');assert.equal(apply[1].p_status,'approved');assert.equal(r.mismatch,false);});
test('CHECK_STATUS uses verification observation time rather than old provider processing time',async()=>{const client=fakeClient(),verifiedAt='2026-09-10T04:20:00.000Z',payments=createPayments({client,provider:wfp,providerConfig:cfg,fetchImpl:fetchFor(signed()),now:()=>verifiedAt});await payments.verifyAndApplyReference('tv-base-1700000000-a1');const apply=client.calls.find(x=>x[0]==='tv_apply_payment_status');assert.equal(apply[1].p_observed_at,verifiedAt);});
test('wrong provider amount is recorded as review and cannot grant access',async()=>{const client=fakeClient(),payments=createPayments({client,provider:wfp,providerConfig:cfg,fetchImpl:fetchFor(signed({amount:'1.00'}))});const r=await payments.verifyAndApplyReference('tv-base-1700000000-a1');const apply=client.calls.find(x=>x[0]==='tv_apply_payment_status');assert.equal(apply[1].p_status,'review');assert.equal(r.mismatch,true);});
test('same provider payload derives the same idempotency event key',async()=>{const payload=signed(),client=fakeClient(),payments=createPayments({client,provider:wfp,providerConfig:cfg,fetchImpl:fetchFor(payload)});await payments.verifyAndApplyReference(payload.orderReference);await payments.verifyAndApplyReference(payload.orderReference);const keys=client.calls.filter(x=>x[0]==='tv_apply_payment_status').map(x=>x[1].p_event_key);assert.equal(keys.length,2);assert.equal(keys[0],keys[1]);});
test('invalid CHECK_STATUS signature changes nothing',async()=>{const payload=signed();payload.merchantSignature='bad';const client=fakeClient(),payments=createPayments({client,provider:wfp,providerConfig:cfg,fetchImpl:fetchFor(payload)});await assert.rejects(payments.verifyAndApplyReference(payload.orderReference),/provider_signature_invalid/);assert.equal(client.calls.some(x=>x[0]==='tv_apply_payment_status'),false);});
test('signed callback is only a trigger; ownership comes from registered order',async()=>{const payload=signed({email:'attacker@example.test'});const client=fakeClient(),payments=createPayments({client,provider:wfp,providerConfig:cfg,fetchImpl:fetchFor(signed())});await payments.applyProviderEvent(payload);assert.equal(client.calls.some(x=>x[0]==='tv_register_order'),false);assert.equal(client.calls.find(x=>x[0]==='tv_payment_order')[1].p_reference,payload.orderReference);});
