const {test}=require('node:test'),assert=require('node:assert/strict');
const {createReconciler,createHandler}=require('../server/reconcile.cjs');
function client(rows){return{rpc:async(name,args)=>name==='tv_reconcile_candidates'?{data:rows,error:null}:{data:null,error:{code:'bad'}}};}
test('reconciliation marks only successfully verified orders',async()=>{const marked=[],p={verifyAndApplyReference:async ref=>{if(ref==='bad')throw Object.assign(new Error('down'),{code:'provider_unavailable'});return{status:'approved'};},markReconciled:async ref=>{marked.push(ref);return{lastReconciledAt:'2026-09-10T00:00:00Z'};}};const run=createReconciler({client:client([{reference:'ok'},{reference:'bad'}]),payments:p}),r=await run({limit:50});assert.equal(r.checked,2);assert.equal(r.succeeded,1);assert.equal(r.failed,1);assert.deepEqual(marked,['ok']);assert.equal(r.results.find(x=>x.reference==='bad').ok,false);});
test('unchanged approved order still advances reconciliation timestamp',async()=>{let marked=0;const p={verifyAndApplyReference:async()=>({status:'approved',duplicate:true}),markReconciled:async()=>{marked++;return{lastReconciledAt:'2026-09-10T00:00:00Z'};}};const r=await createReconciler({client:client([{reference:'same'}]),payments:p})({limit:1});assert.equal(r.succeeded,1);assert.equal(marked,1);});
test('invalid provider verification never marks last_reconciled_at',async()=>{let marked=false;const p={verifyAndApplyReference:async()=>{throw Object.assign(new Error('bad signature'),{code:'provider_signature_invalid'});},markReconciled:async()=>{marked=true;}};await createReconciler({client:client([{reference:'signed-bad'}]),payments:p})({limit:1});assert.equal(marked,false);});
function res(){return{statusCode:0,headers:{},setHeader(k,v){this.headers[k.toLowerCase()]=v;},status(n){this.statusCode=n;return this;},json(b){this.body=b;return this;}};}
test('cron endpoint requires constant-time bearer secret contract',async()=>{const secret='c'.repeat(40),handler=createHandler({secret,run:async()=>({checked:0,succeeded:0,failed:0,results:[]})});let r=res();await handler({method:'GET',headers:{authorization:'Bearer nope'},query:{}},r);assert.equal(r.statusCode,403);r=res();await handler({method:'GET',headers:{authorization:'Bearer '+secret},query:{}},r);assert.equal(r.statusCode,200);assert.equal(r.body.ok,true);});
test('cron limit is bounded',async()=>{const secret='c'.repeat(40),handler=createHandler({secret,run:createReconciler({client:client([]),payments:{}})}),r=res();await handler({method:'GET',headers:{authorization:'Bearer '+secret},query:{limit:'101'}},r);assert.equal(r.statusCode,400);});
