const {test}=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const wfp=require('../server/wayforpay.cjs');
const sign=(secret,parts)=>crypto.createHmac('md5',secret).update(parts.join(';'),'utf8').digest('hex');

test('TRANSACTION_LIST signature',()=>{const r=wfp.transactionListRequest({merchantAccount:'m',secret:'s'},{dateBegin:1700000000,dateEnd:1700086400});assert.equal(r.transactionType,'TRANSACTION_LIST');assert.equal(r.merchantSignature,sign('s',['m','1700000000','1700086400']));});
test('CHECK_STATUS signature',()=>{const r=wfp.checkStatusRequest({merchantAccount:'m',secret:'s'},'tv-base-1-a');assert.equal(r.merchantSignature,sign('s',['m','tv-base-1-a']));});
test('modern product mapping is exact',()=>{assert.equal(wfp.productFromReference('tv-base-1-a'),'mini-base');assert.equal(wfp.productFromReference('tv-pro-1-a'),'mini-pro');assert.equal(wfp.productFromReference('tv-upgrade-1-a'),'mini-upgrade');assert.equal(wfp.productFromReference('tv-atlas-1-a'),'atlas-28d');assert.equal(wfp.productFromReference('legacy-1'),null);assert.equal(wfp.productFromReference('tv-base-oops'),null);});
test('refundAmount overrides Approved',()=>{assert.equal(wfp.providerStatus({transactionStatus:'Approved',refundAmount:'1.00'}),'refunded');});
test('status response uses documented signed field order',()=>{const p={merchantAccount:'m',orderReference:'tv-base-1-a',amount:'15.00',currency:'USD',authCode:'A1',cardPan:'44****1111',transactionStatus:'Approved',reasonCode:1100};p.merchantSignature=sign('s',['m','tv-base-1-a','15.00','USD','A1','44****1111','Approved','1100']);assert.equal(wfp.verifyStatusResponse({merchantAccount:'m',secret:'s'},p),true);assert.equal(wfp.verifyStatusResponse({merchantAccount:'m',secret:'s'},{...p,amount:'1.00'}),false);});
test('money parser never needs floating point multiplication',()=>{assert.equal(wfp.parseAmountMinor('15'),1500);assert.equal(wfp.parseAmountMinor('15.5'),1550);assert.equal(wfp.parseAmountMinor('15.05'),1505);assert.throws(()=>wfp.parseAmountMinor('15.005'),/invalid_amount/);});
test('legacy mapping requires exactly one exact rule',()=>{const tx={orderReference:'legacy-77',amount:'15.00',currency:'USD',email:'buyer@example.test',createdDate:1700000000,transactionStatus:'Approved'};const one=wfp.normalizeHistoryTransaction(tx,[{productId:'mini-base',amountMinor:1500,currency:'USD',referencePattern:'^legacy-'}]);assert.equal(one.productId,'mini-base');assert.equal(one.classification,'mapped');const ambiguous=wfp.normalizeHistoryTransaction(tx,[{productId:'mini-base',amountMinor:1500,currency:'USD'},{productId:'mini-pro',amountMinor:1500,currency:'USD'}]);assert.equal(ambiguous.productId,null);assert.equal(ambiguous.classification,'review');});
test('modern reference wins before legacy rules',()=>{const tx={orderReference:'tv-pro-1700000000-a1',amount:'25.00',currency:'USD',email:'buyer@example.test',createdDate:1700000000,transactionStatus:'Approved'};const n=wfp.normalizeHistoryTransaction(tx,[{productId:'mini-base',amountMinor:2500,currency:'USD'}]);assert.equal(n.productId,'mini-pro');assert.equal(n.amountMinor,2500);assert.equal(n.buyerEmail,'buyer@example.test');assert.equal(n.purchasedAt,'2023-11-14T22:13:20.000Z');});
