'use strict';
const crypto=require('node:crypto');
const wfp=require('./wayforpay.cjs');
const {serviceClient}=require('./service-supabase.cjs');
const PRODUCTS=new Set(['mini-base','mini-pro','mini-upgrade','atlas-28d']);
const MAX_HISTORY_SECONDS=31*24*60*60;
const sha=value=>crypto.createHash('sha256').update(typeof value==='string'?value:JSON.stringify(value),'utf8').digest('hex');
const error=(code,status=500)=>{const e=new Error(code);e.code=code;e.status=status;return e;};
function email(v){const s=String(v||'').trim().toLowerCase();if(s.length>254||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s))throw error('invalid_email',400);return s;}
function iso(v){const d=typeof v==='number'?new Date(v<1e12?v*1000:v):new Date(v);if(Number.isNaN(d.getTime()))throw error('invalid_timestamp',400);return d.toISOString();}
function paymentConfig(env=process.env){let legacyRules=[];try{legacyRules=JSON.parse(env.WAYFORPAY_LEGACY_RULES_JSON||'[]');if(!Array.isArray(legacyRules))legacyRules=[];}catch{throw error('invalid_legacy_rules',500);}const merchantAccount=String(env.WAYFORPAY_MERCHANT_ACCOUNT||''),secret=String(env.WAYFORPAY_SECRET_KEY||'');if(!merchantAccount||!secret)throw error('wayforpay_not_configured',503);return{merchantAccount,secret,legacyRules};}
async function rpc(client,name,args){const {data,error:dbError}=await client.rpc(name,args);if(dbError){const status=dbError.code==='22023'?400:dbError.code==='42501'?403:503;const e=error(status===400?'invalid_payment_data':status===403?'admin_required':'payment_database_unavailable',status);e.cause=dbError;throw e;}return data;}
async function optionalOrder(client,reference){const {data,error:dbError}=await client.rpc('tv_payment_order',{p_provider:'wayforpay',p_reference:reference});if(!dbError)return data;if(dbError.code==='22023')return null;throw error('payment_database_unavailable',503);}
function validateHistoryRange({dateBegin,dateEnd}){if(!Number.isInteger(dateBegin)||!Number.isInteger(dateEnd)||dateBegin<0||dateEnd<dateBegin||dateEnd-dateBegin>MAX_HISTORY_SECONDS)throw error('invalid_history_window',400);return{dateBegin,dateEnd};}
function listRows(payload){if(Array.isArray(payload))return payload;for(const key of ['transactionList','transactions','list'])if(Array.isArray(payload?.[key]))return payload[key];return[];}
function accessPreview(productId,purchasedAt){if(!purchasedAt)return{access:'none',expiresAt:null,lifetime:false};if(productId==='mini-base'||productId==='mini-pro'){const expires=new Date(new Date(purchasedAt).getTime()+210*86400000).toISOString();return{access:'atlas',expiresAt:expires,lifetime:false};}if(productId==='atlas-28d')return{access:'atlas',expiresAt:null,lifetime:true};return{access:'none',expiresAt:null,lifetime:false};}
function canonicalRows(rows){return rows.map(r=>({reference:r.reference,productId:r.productId,productHint:r.productHint,amountMinor:r.amountMinor,currency:r.currency,status:r.status,buyerEmail:r.buyerEmail,purchasedAt:r.purchasedAt,classification:r.classification})).sort((a,b)=>(a.reference||'').localeCompare(b.reference||'')||(a.purchasedAt||'').localeCompare(b.purchasedAt||''));}
function createPayments({client,provider=wfp,providerConfig,fetchImpl=globalThis.fetch,now=()=>new Date()}={}){
 const c=client||serviceClient();let cfg=providerConfig;const getCfg=()=>cfg||(cfg=paymentConfig());
 async function registerTrustedOrder(input){const reference=String(input?.reference||'').trim(),buyerEmail=email(input?.email),productId=String(input?.productId||'');if(!reference||reference.length>180||!PRODUCTS.has(productId)||!Number.isInteger(input?.amountMinor)||input.amountMinor<=0)throw error('invalid_order',400);const currency=String(input.currency||'').trim().toUpperCase();if(!/^[A-Z]{3}$/.test(currency))throw error('invalid_currency',400);const purchasedAt=iso(input.purchasedAt),identity={reference,email:buyerEmail,productId,amountMinor:input.amountMinor,currency,purchasedAt};return rpc(c,'tv_register_order',{p_provider:'wayforpay',p_reference:reference,p_buyer_email:buyerEmail,p_product_id:productId,p_product_hint:null,p_amount_minor:input.amountMinor,p_currency:currency,p_purchased_at:purchasedAt,p_event_key:'checkout:'+sha(reference).slice(0,48),p_payload_hash:sha(identity)});}
 async function registeredOrder(reference){return rpc(c,'tv_payment_order',{p_provider:'wayforpay',p_reference:String(reference||'')});}
 async function verifyAndApplyReference(reference){reference=String(reference||'').trim();if(!reference)throw error('invalid_reference',400);const providerCfg=getCfg(),expected=await registeredOrder(reference),payload=await provider.fetchCheckStatus(providerCfg,reference,fetchImpl);if(!provider.verifyStatusResponse(providerCfg,payload))throw error('provider_signature_invalid',502);if(String(payload.orderReference||'')!==reference)throw error('provider_reference_mismatch',502);let amountMinor=null;try{amountMinor=provider.parseAmountMinor(payload.amount);}catch{}const currency=String(payload.currency||'').toUpperCase(),providerState=provider.providerStatus(payload);const mismatch=amountMinor===null||amountMinor!==Number(expected.amountMinor)||currency!==String(expected.currency||'').toUpperCase();const finalState=mismatch?'review':providerState,observedAt=iso(now());const fingerprint={merchantAccount:payload.merchantAccount,orderReference:payload.orderReference,amount:payload.amount,currency:payload.currency,authCode:payload.authCode,cardPan:payload.cardPan,transactionStatus:payload.transactionStatus,reasonCode:payload.reasonCode,refundAmount:payload.refundAmount??null,merchantSignature:payload.merchantSignature};const result=await rpc(c,'tv_apply_payment_status',{p_provider:'wayforpay',p_reference:reference,p_status:finalState,p_observed_at:observedAt,p_event_key:'status:'+sha(fingerprint).slice(0,48),p_payload_hash:sha(fingerprint)});return{reference,status:result.status,providerStatus:providerState,mismatch,duplicate:result.duplicate===true};}
 async function applyProviderEvent(callbackPayload){const providerCfg=getCfg();if(!provider.verifyStatusResponse(providerCfg,callbackPayload))throw error('bad_signature',400);const reference=String(callbackPayload?.orderReference||'').trim();if(!reference)throw error('invalid_reference',400);return verifyAndApplyReference(reference);}
 async function registry(actorId){return rpc(c,'tv_admin_registry',{p_actor:actorId});}
 async function buildHistoryPreview(range){range=validateHistoryRange(range);const providerCfg=getCfg(),payload=await provider.fetchTransactionList(providerCfg,range,fetchImpl),normalized=listRows(payload).map(tx=>provider.normalizeHistoryTransaction(tx,providerCfg.legacyRules)),canonical=canonicalRows(normalized),digest=sha(canonical);const items=[];for(const row of canonical){let local=null;if(row.reference)try{local=await optionalOrder(c,row.reference);}catch(e){throw e;}const access=accessPreview(row.productId,row.purchasedAt);let classification=row.classification==='review'?'review':row.status;if(local){const sameIdentity=String(local.productId||'')===String(row.productId||'')&&Number(local.amountMinor)===Number(row.amountMinor)&&String(local.currency||'')===String(row.currency||'')&&String(local.purchasedAt||'')===String(row.purchasedAt||'');classification=sameIdentity?'already_imported':'conflict';}else if(row.classification!=='review'&&row.status==='approved'){classification=access.expiresAt&&new Date(access.expiresAt)<=new Date()?'expired_entitlement':'new_approved';}items.push({...row,...access,classification,existingOrderId:local?.orderId||null});}return{dateBegin:range.dateBegin,dateEnd:range.dateEnd,digest,items};}
 async function historyCommit({actorId,dateBegin,dateEnd,digest}){if(!/^[a-f0-9]{64}$/.test(String(digest||'')))throw error('invalid_digest',400);const preview=await buildHistoryPreview({dateBegin,dateEnd});if(preview.digest!==digest)throw error('history_changed',409);const results=[];for(const row of canonicalRows(preview.items)){const persistable=!!row.reference&&!!row.buyerEmail&&Number.isInteger(row.amountMinor)&&row.amountMinor>0&&/^[A-Z]{3}$/.test(row.currency||'')&&!!row.purchasedAt;if(!persistable){results.push({reference:row.reference||null,status:'review',persisted:false});continue;}const registerArgs={p_provider:'wayforpay',p_reference:row.reference,p_buyer_email:row.buyerEmail,p_product_id:row.productId||null,p_product_hint:row.productHint||null,p_amount_minor:row.amountMinor,p_currency:row.currency,p_purchased_at:row.purchasedAt,p_event_key:'history:'+sha(row).slice(0,48),p_payload_hash:sha(row)};try{await rpc(c,'tv_register_order',registerArgs);if(!row.productId){await rpc(c,'tv_apply_payment_status',{p_provider:'wayforpay',p_reference:row.reference,p_status:'review',p_observed_at:row.purchasedAt,p_event_key:'history-review:'+sha(row).slice(0,40),p_payload_hash:sha({review:row})});results.push({reference:row.reference,status:'review',persisted:true});}else{const applied=await verifyAndApplyReference(row.reference);results.push({reference:row.reference,status:applied.status,persisted:true});}}catch(e){if(e.code==='invalid_payment_data'){results.push({reference:row.reference,status:'conflict',persisted:false});continue;}throw e;}}await rpc(c,'tv_admin_audit',{p_actor:actorId,p_action:'history_import_commit',p_detail:{dateBegin,dateEnd,digest,count:results.length}});return{digest,results};}
 async function reconcileReference(reference){return verifyAndApplyReference(reference);}
 async function transferEntitlement({actorId,orderId,resourceKey,targetUserId,reason}){return rpc(c,'tv_admin_transfer_entitlement',{p_actor:actorId,p_order_id:orderId,p_resource_key:resourceKey,p_target_user:targetUserId,p_reason:reason});}
 async function setRevoked({actorId,orderId,resourceKey,revoked,reason}){return rpc(c,'tv_admin_set_revoked',{p_actor:actorId,p_order_id:orderId,p_resource_key:resourceKey,p_revoked:revoked,p_reason:reason});}
 async function markReconciled(reference,observedAt=new Date().toISOString()){return rpc(c,'tv_mark_reconciled',{p_provider:'wayforpay',p_reference:reference,p_observed_at:iso(observedAt)});}
 return{registerTrustedOrder,registeredOrder,verifyAndApplyReference,applyProviderEvent,registry,buildHistoryPreview,historyCommit,reconcileReference,transferEntitlement,setRevoked,markReconciled,get config(){return cfg;}};
}
let singleton;const defaults=()=>singleton||(singleton=createPayments());
module.exports={paymentConfig,createPayments,registerTrustedOrder:input=>defaults().registerTrustedOrder(input),verifyAndApplyReference:reference=>defaults().verifyAndApplyReference(reference),applyProviderEvent:payload=>defaults().applyProviderEvent(payload),sha,validateHistoryRange,accessPreview,canonicalRows};
