'use strict';
const crypto=require('node:crypto');
const {serviceClient}=require('./service-supabase.cjs');
const {createPayments}=require('./payments.cjs');
const fail=(status,code)=>{const e=new Error(code);e.status=status;e.code=code;throw e;};
function same(a,b){const x=Buffer.from(String(a||'')),y=Buffer.from(String(b||''));return x.length===y.length&&crypto.timingSafeEqual(x,y);}
async function candidates(client,limit){const {data,error}=await client.rpc('tv_reconcile_candidates',{p_limit:limit});if(error)throw fail(503,'payment_database_unavailable');return Array.isArray(data)?data:[];}
function createReconciler({client,payments}={}){const c=client||serviceClient(),p=payments||createPayments({client:c});return async function run({limit=50}={}){if(!Number.isInteger(limit)||limit<1||limit>100)throw fail(400,'invalid_limit');const rows=await candidates(c,limit),results=[];for(const row of rows){try{const applied=await p.verifyAndApplyReference(row.reference);const marked=await p.markReconciled(row.reference,new Date().toISOString());results.push({reference:row.reference,ok:true,status:applied.status,lastReconciledAt:marked.lastReconciledAt||null});}catch(e){results.push({reference:row.reference,ok:false,error:e.code||'provider_unavailable'});}}return{checked:results.length,succeeded:results.filter(x=>x.ok).length,failed:results.filter(x=>!x.ok).length,results};};}
function createHandler({run,secret=String(process.env.CRON_SECRET||'')}={}){const reconcile=run||createReconciler();return async(req,res)=>{res.setHeader('Cache-Control','private, no-store, max-age=0');const send=(n,b)=>res.status(n).json(b);try{if(req.method!=='GET'){res.setHeader('Allow','GET');throw fail(405,'method_not_allowed');}if(!secret||secret.length<32)throw fail(503,'cron_not_configured');if(!same(req.headers.authorization,'Bearer '+secret))throw fail(403,'cron_forbidden');const limit=req.query?.limit===undefined?50:Number(req.query.limit);return send(200,{ok:true,result:await reconcile({limit})});}catch(e){const status=Number.isInteger(e.status)?e.status:500;return send(status,{error:status<500&&e.code?e.code:status===503&&e.code?e.code:'server_error'});}};}
module.exports={createReconciler,createHandler};
